### PR TITLE
Check for exit status of startup script

### PR DESCRIPTION
**Pull request by ricardobranco777**
Exit with the same exit status of the startup script, or 128 + signal number if the script was terminated by a signal. This follows some shells convention.

The exit(1); was changed to exit(-1); In the shell $? would appear as 255.

### CODE REVIEW

**Comment by chazomaticus** [comment]
Thanks for this, I should have time to look at it soon!

**Comment by chazomaticus** [comment]
Hi @ricardobranco777, I finally dug into this a little this weekend, and I found a couple things I wanted to take care of.  The way it was structured, it wouldn't return the startup script's error if minit received a SIGTERM before the startup process finished.  I also felt like it might make more sense for the shutdown script to be guaranteed to run, so you can leave all your cleanup logic in one place (i.e. so you don't have to worry about the startup script cleaning up after itself if it fails halfway through, for example).

I took your patch but then as I was thinking about how to structure things to fix those issues, I found myself writing pseudocode, then that kept turning into real code, and, well, I ended up rewriting most of minit.  It's up in the [`propagate-startup-errors`](https://github.com/chazomaticus/minit/blob/propagate-startup-errors/minit.c) branch (and see commit [`c966aa8`](https://github.com/chazomaticus/minit/commit/c966aa8e0985a00f8292b43e542603bb718fcebb) for a briefer explanation than I've given here).

I like how there are fewer loops, but now each one does more--the code is a bit harder to follow, because it now has to track more state.  On my machine, the generated executable is also about 4kb bigger (~10kb vs. ~6kb before), which is annoying but obviously not a huge deal.

Anyway, I'd appreciate it if you (or anyone!) took a look and let me know what you think.  So far I feel like this is a good change, and I'm stoked about landing it.  Thanks again for your help!

**Comment by ricardobranco777** [comment]
There are many use cases for the shutdown script, such as cleanly shutdown databases.  The startup script knows better when it comes to the return status of the commands executed, and so on.  It could get messy to pass this information to the shutdown script.

As for SIGTERM, as it is a catchable signal, it would be better to expect that the startup script handle itself if needed.

**Comment by chazomaticus** [comment]
I agree completely about the startup/shutdown scripts.  I guess I was saying that ensuring the shutdown script always runs means you can do it either way, letting the startup script handle its own failures, or letting the shutdown script handle cleaning everything up regardless.

Thanks again for your help!

**Pull request merged**
